import { createPortal } from "react-dom";
import { XIcon, PrinterIcon, SendIcon, FileSpreadsheetIcon, CheckCircle2Icon } from "lucide-react";
import { Button } from "@/components/ui/button";
import { exportTransactionsToExcel } from "@/lib/cash-export-utils";

export function CashPrintStatementModal({
  isOpen,
  onClose,
  transactions = [],
  partyName = "All Parties",
  startDate = "",
  endDate = "",
  cashierName = "Active Cashier",
}) {
  if (!isOpen || typeof window === "undefined") return null;

  const sortedTransactions = [...transactions].sort((a, b) => {
    const dateA = new Date(a.transactionDate || a.date || a.createdAt || Date.now()).getTime();
    const dateB = new Date(b.transactionDate || b.date || b.createdAt || Date.now()).getTime();
    return (isNaN(dateA) ? 0 : dateA) - (isNaN(dateB) ? 0 : dateB);
  });

  let running = 0;
  const computedRows = sortedTransactions.map((t) => {
    const isInflow = t.type === "Received" || t.transactionType === "Cash Received" || t.type === "cash_in";
    const amountNum = Number(t.amount || 0);
    const inflow = isInflow ? amountNum : 0;
    const outflow = !isInflow ? amountNum : 0;
    running = running + inflow - outflow;

    const parsedDate = new Date(t.transactionDate || t.date || t.createdAt || Date.now());
    const validDate = isNaN(parsedDate.getTime()) ? new Date() : parsedDate;
    const formattedDate = validDate.toLocaleDateString("en-GB");

    return {
      ...t,
      date: validDate,
      formattedDate,
      particulars: t.particulars || t.description || t.notes || (isInflow ? `Received from ${t.partyName || "Party"}` : `Paid to ${t.partyName || "Party"}`),
      reference: t.reference || t.voucherNumber || t.referenceNumber || t._id?.slice(-6) || "-",
      inflow,
      outflow,
      balance: running,
    };
  });

  const totalInflow = computedRows.reduce((sum, r) => sum + r.inflow, 0);
  const totalOutflow = computedRows.reduce((sum, r) => sum + r.outflow, 0);
  const closingBalance = running;
  const finalBalance = running;

  const handlePrint = () => {
    const orig = document.title;
    const party = (partyName || "Cash_Transactions").replace(/[^a-zA-Z0-9-_]/g, "_");
    document.title = `Al_Khaleej_Cash_Ledger_${party}`;
    window.print();
    const restore = () => {
      document.title = orig;
      window.removeEventListener("afterprint", restore);
    };
    window.addEventListener("afterprint", restore);
    setTimeout(restore, 2000);
  };

  const handleExportExcel = () => {
    const excelData = computedRows.map((r, idx) => ({
      "Sr #": idx + 1,
      Date: r.formattedDate,
      "Party / Customer": r.partyName || r.partyId?.name || "Direct Cash",
      "Voucher #": r.reference,
      Description: r.particulars,
      "Cash Inflow (Debit)": r.inflow,
      "Cash Outflow (Credit)": r.outflow,
      "Closing Balance": r.balance,
    }));
    exportTransactionsToExcel(
      excelData,
      `Cash_Subsidiary_Ledger_${new Date().toISOString().slice(0, 10)}.xlsx`
    );
  };

  const handleShareWhatsApp = () => {
    const text = `*AL KHALEEJ LUBRICANTS - CASH STATEMENT*\n*Party:* ${partyName}\n*Period:* ${startDate || "Start"} to ${endDate || "Today"}\n*Total Inflow:* Rs ${totalInflow.toLocaleString()}\n*Total Outflow:* Rs ${totalOutflow.toLocaleString()}\n*Closing Balance:* Rs ${closingBalance.toLocaleString()}\n*Generated by:* ${cashierName}`;
    window.open(`https://api.whatsapp.com/send?text=${encodeURIComponent(text)}`, "_blank");
  };

  const currentUserStr = localStorage.getItem("user");
  const parsedUser = currentUserStr ? JSON.parse(currentUserStr) : null;
  const activeOperator = parsedUser?.name || cashierName;

  const modalContent = (
    <div className="print-portal fixed inset-0 z-[100] flex items-center justify-center bg-black/80 backdrop-blur-xs p-4 overflow-y-auto print:p-0 print:m-0 print:bg-white print:static print:overflow-visible print:block print:w-full print:h-auto">
      <style>{`
        @media print {
          @page {
            size: A4 portrait;
            margin: 4mm 6mm;
          }
          html, body {
            background: white !important;
            color: black !important;
            margin: 0 !important;
            padding: 0 !important;
            width: 100% !important;
            -webkit-print-color-adjust: exact !important;
            print-color-adjust: exact !important;
          }
          .print-portal {
            position: static !important;
            display: block !important;
            background: white !important;
            padding: 0 !important;
            margin: 0 !important;
            overflow: visible !important;
            width: 100% !important;
            height: auto !important;
            max-height: none !important;
            border: none !important;
            box-shadow: none !important;
          }
          .a4-sheet {
            display: block !important;
            width: 100% !important;
            max-width: 100% !important;
            padding: 0 !important;
            margin: 0 !important;
            border: none !important;
            box-shadow: none !important;
            background: white !important;
            color: black !important;
          }
          .print\\:hidden,
          [class*="print:hidden"] {
            display: none !important;
          }
        }
      `}</style>

      <div className="w-full max-w-4xl max-h-[90vh] rounded-2xl border border-border bg-background shadow-2xl flex flex-col my-auto print:border-none print:shadow-none print:w-full print:max-w-none print:max-h-none print:my-0 print:block print:bg-white">
        <div className="w-full flex items-center justify-between border-b border-border p-3.5 print:hidden bg-card rounded-t-2xl shrink-0">
          <div className="flex items-center gap-2 text-foreground font-semibold text-sm">
            <CheckCircle2Icon className="size-4 text-emerald-500" />
            <span>Subsidiary Ledger for Cash Transactions (A4 Standard)</span>
          </div>
          <div className="flex items-center gap-2">
            <Button
              size="sm"
              onClick={handleShareWhatsApp}
              className="gap-1.5 text-xs cursor-pointer bg-emerald-600 hover:bg-emerald-700 text-white"
            >
              <SendIcon className="size-3.5" />
              <span>Share WhatsApp</span>
            </Button>
            <Button
              variant="outline"
              size="sm"
              onClick={handleExportExcel}
              className="gap-1.5 text-xs cursor-pointer"
            >
              <FileSpreadsheetIcon className="size-3.5 text-emerald-500" />
              <span>Export Excel</span>
            </Button>
            <Button
              size="sm"
              onClick={handlePrint}
              className="gap-1.5 text-xs cursor-pointer bg-primary text-primary-foreground font-medium"
            >
              <PrinterIcon className="size-3.5" />
              <span>Print A4 Document</span>
            </Button>
            <Button variant="ghost" size="icon-sm" onClick={onClose} className="cursor-pointer">
              <XIcon className="size-4" />
            </Button>
          </div>
        </div>

        <div className="w-full flex-1 overflow-y-auto p-4 md:p-6 flex flex-col items-center print:overflow-visible print:p-0">
          <div
            className="w-full max-w-[210mm] bg-white text-black p-6 md:p-8 rounded-xl shadow-lg border border-border/80 font-sans text-xs print:shadow-none print:border-none print:p-0 a4-sheet relative notranslate"
          dir="ltr"
          lang="en"
        >
          <div className="flex justify-end text-[11px] font-medium text-black pb-1">
            Annex 10
          </div>

          <div className="text-center pb-4">
            <h1 className="text-sm md:text-base font-bold uppercase tracking-wider text-black">
              CASH BOOK STATEMENT
            </h1>
            <p className="text-[11px] text-gray-700 font-medium">
              AL KHALEEJ LUBRICANTS
            </p>
          </div>

          <div className="border border-black mb-4 text-[11px] leading-relaxed">
            <div className="grid grid-cols-1 divide-y divide-black">
              <div className="px-3 py-1 flex">
                <span className="w-48 font-semibold text-black">Branch / Location:</span>
                <span className="font-bold uppercase text-black">Main Depot / POS Register</span>
              </div>
              <div className="px-3 py-1 flex">
                <span className="w-48 font-semibold text-black">Address:</span>
                <span className="text-black">Plot #44/B, Korangi Industrial Area, Karachi, Pakistan</span>
              </div>
              <div className="px-3 py-1 flex">
                <span className="w-48 font-semibold text-black">Cashier / Operator:</span>
                <span className="font-semibold text-black uppercase">{activeOperator}</span>
              </div>
              <div className="px-3 py-1 flex">
                <span className="w-48 font-semibold text-black">Account / Party Name:</span>
                <span className="font-bold text-black uppercase">{partyName}</span>
              </div>
              <div className="px-3 py-1 flex">
                <span className="w-48 font-semibold text-black">Period:</span>
                <span className="text-black">
                  {startDate ? new Date(startDate).toLocaleDateString("en-GB") : "Start"} — {endDate ? new Date(endDate).toLocaleDateString("en-GB") : new Date().toLocaleDateString("en-GB")}
                </span>
              </div>
            </div>
          </div>

          <div className="mb-6">
            <table className="w-full border-collapse border border-black text-[11px]">
              <thead>
                <tr className="border-b border-black text-center font-bold">
                  <th rowSpan={2} className="border-r border-black p-2 w-20 text-center">
                    Date
                  </th>
                  <th rowSpan={2} className="border-r border-black p-2 text-left">
                    Description
                  </th>
                  <th rowSpan={2} className="border-r border-black p-2 w-20 text-center">
                    Voucher #
                  </th>
                  <th colSpan={3} className="border-b border-black p-1.5 text-center">
                    Amount (Rs)
                  </th>
                </tr>
                <tr className="border-b border-black font-bold text-center">
                  <th className="border-r border-black p-1.5 w-28 text-right">
                    Cash In
                  </th>
                  <th className="border-r border-black p-1.5 w-28 text-right">
                    Cash Out
                  </th>
                  <th className="p-1.5 w-28 text-right">
                    Balance
                  </th>
                </tr>
              </thead>
              <tbody className="divide-y divide-black">
                {computedRows.length === 0 ? (
                  <tr>
                    <td colSpan={6} className="p-6 text-center text-gray-500 border border-black">
                      No cash ledger records found for this period.
                    </td>
                  </tr>
                ) : (
                  computedRows.map((row, idx) => (
                    <tr key={idx} className="border-b border-black">
                      <td className="border-r border-black p-1.5 text-center font-mono">
                        {row.date.toLocaleDateString("en-GB")}
                      </td>
                      <td className="border-r border-black p-1.5 font-medium leading-tight">
                        {row.particulars}
                      </td>
                      <td className="border-r border-black p-1.5 text-center font-mono text-[10px]">
                        {row.reference}
                      </td>
                      <td className="border-r border-black p-1.5 text-right font-mono">
                        {row.inflow > 0
                          ? row.inflow.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })
                          : "-"}
                      </td>
                      <td className="border-r border-black p-1.5 text-right font-mono">
                        {row.outflow > 0
                          ? row.outflow.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })
                          : "-"}
                      </td>
                      <td className="p-1.5 text-right font-mono font-bold">
                        {row.balance.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}
                      </td>
                    </tr>
                  ))
                )}

                <tr className="border-t-2 border-black font-bold bg-gray-50">
                  <td colSpan={3} className="border-r border-black p-2 text-right uppercase">
                    Total:
                  </td>
                  <td className="border-r border-black p-2 text-right font-mono">
                    {totalInflow.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}
                  </td>
                  <td className="border-r border-black p-2 text-right font-mono">
                    {totalOutflow.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}
                  </td>
                  <td className="p-2 text-right font-mono font-bold">
                    {finalBalance.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}
                  </td>
                </tr>
              </tbody>
            </table>
          </div>

          <div className="pt-10 grid grid-cols-2 gap-12 text-xs">
            <div className="space-y-6">
              <p className="font-semibold text-[11px]">Prepared by:</p>
              <div className="pt-4 border-t border-black w-4/5">
                <p className="font-bold uppercase text-[11px]">{activeOperator}</p>
                <p className="text-[10px] text-gray-700">Cashier Signature</p>
              </div>
            </div>

            <div className="space-y-6 text-right flex flex-col items-end">
              <p className="font-semibold text-[11px]">Approved by:</p>
              <div className="pt-4 border-t border-black w-4/5 text-right">
                <p className="font-bold uppercase text-[11px]">AL KHALEEJ ACCOUNTS</p>
                <p className="text-[10px] text-gray-700">Authorized Signature</p>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div className="w-full flex items-center justify-end gap-2 p-3.5 border-t border-border bg-card rounded-b-2xl print:hidden shrink-0">
        <Button variant="outline" size="sm" onClick={onClose} className="cursor-pointer text-xs">
          Close Preview
        </Button>
        <Button
          size="sm"
          onClick={handlePrint}
          className="cursor-pointer text-xs gap-1.5 bg-primary text-primary-foreground font-medium"
        >
          <PrinterIcon className="size-3.5" />
          <span>Print A4 Document</span>
        </Button>
      </div>
    </div>
  </div>
);

return createPortal(modalContent, document.body);
}
